In [3]:
! pip install missingno

Collecting missingno
  Downloading missingno-0.5.1-py3-none-any.whl (8.7 kB)
Requirement already satisfied: numpy in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from missingno) (1.18.5)
Requirement already satisfied: scipy in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from missingno) (1.5.0)
Requirement already satisfied: matplotlib in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from missingno) (3.2.2)
Requirement already satisfied: seaborn in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from missingno) (0.11.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from matplotlib->missingno) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from matplotlib->missingno) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from matplotlib->missingno) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from matplotlib->missingno) (2.8.1)
Requirement already satisfied: pandas>=0.23 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from seaborn->missingno) (1.0.5)
Requirement already satisfied: six in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from cycler>=0.10->matplotlib->missingno) (1.15.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\carlalorente\anaconda3\envs\pythondata\lib\site-packages (from pandas>=0.23->seaborn->missingno) (2020.1)
Installing collected packages: missingno
Successfully installed missingno-0.5.1

In [4]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine 
import missingno as msno
from zipfile import ZipFile
import re
from bs4 import BeautifulSoup
import requests

In [6]:
def API_men(url, headers):
    resp_men = requests.get(url,headers=headers).json()
    result_len=len(resp_men['products'])
    articleCode=[resp_men["products"][i]["articleCode"] for i in range(result_len)]
    title=[resp_men["products"][i]["title"] for i in range(result_len)]
    category=[resp_men["products"][i]["category"] for i in range(result_len)]
    price=[resp_men['products'][i]['price'] for i in range(result_len)]
    
    list_dict={"articleCode":articleCode,
               "title":title,
               "category":category,
               "price":price,
               }                      
                                    
                                    
    list_men_df=pd.DataFrame(list_dict)
    #list_df.to_csv("Resources/women_article.csv",index=False)
    return list_men_df

In [7]:
headers = {'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'}
url='https://www2.hm.com/en_us/men/products/view-all/_jcr_content/main/productlisting_fa5b.display.json?sort=stock&image-size=small&image=model&offset=252&page-size=2068'
men_article_df=API_men(url,headers)

In [8]:
men_article_df

,articleCode,title,category,price
0,1003594001,Overalls,men_trousers,$ 39.99
1,1032522013,Relaxed Fit Cotton T-shirt,men_tshirtstanks_shortsleeve,$ 12.99
2,1067651001,Oversized Fit Rugby Shirt,men_tshirtstanks_longsleeve,$ 24.99
3,1079455001,Relaxed Fit Twill Pants,men_trousers,$ 34.99
4,1003594003,Overalls,men_trousers,$ 39.99
...,...,...,...,...
2062,0701057016,Patterned Socks,men_socks,$ 6.99
2063,0995680003,Slim Fit Sports Joggers,men_sport_bottoms,$ 29.99
2064,0742742024,Rib-knit Hat,men_accessories_hatscaps_beanie,$ 9.99
2065,1042110001,Fast-drying Running Shorts,men_shorts_sport,$ 29.99
2066,1042110002,Fast-drying Running Shorts,men_shorts_sport,$ 29.99

In [9]:
def price_maker(x):
    return float(x.split()[-1])

In [10]:
men_article_df['price($)']=men_article_df["price"].apply(price_maker)

In [11]:
men_article_df.drop('price',axis=1, inplace=True)
men_article_df

,articleCode,title,category,price($)
0,1003594001,Overalls,men_trousers,39.99
1,1032522013,Relaxed Fit Cotton T-shirt,men_tshirtstanks_shortsleeve,12.99
2,1067651001,Oversized Fit Rugby Shirt,men_tshirtstanks_longsleeve,24.99
3,1079455001,Relaxed Fit Twill Pants,men_trousers,34.99
4,1003594003,Overalls,men_trousers,39.99
...,...,...,...,...
2062,0701057016,Patterned Socks,men_socks,6.99
2063,0995680003,Slim Fit Sports Joggers,men_sport_bottoms,29.99
2064,0742742024,Rib-knit Hat,men_accessories_hatscaps_beanie,9.99
2065,1042110001,Fast-drying Running Shorts,men_shorts_sport,29.99
2066,1042110002,Fast-drying Running Shorts,men_shorts_sport,29.99

In [13]:
men_article_df.to_csv("Resources/men_article.csv",index=False)